var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/send-verification/route.js")
R.c("server/chunks/node_modules_resend_dist_index_mjs_542e98f2._.js")
R.c("server/chunks/node_modules_next_604ac18b._.js")
R.c("server/chunks/node_modules_@neondatabase_serverless_index_mjs_2c73916b._.js")
R.c("server/chunks/node_modules_drizzle-orm_d0018caa._.js")
R.c("server/chunks/node_modules_tailwind-merge_dist_bundle-mjs_mjs_c3b2c59f._.js")
R.c("server/chunks/node_modules_clsx_dist_clsx_mjs_b86e21b8._.js")
R.c("server/chunks/[root-of-the-server]__b7ac5899._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_send-verification_route_actions_73e3007f.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/send-verification/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/send-verification/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
