var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...all]/route.js")
R.c("server/chunks/node_modules_ff8a201f._.js")
R.c("server/chunks/node_modules_next_dist_a206e2cf._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@better-auth_core_dist_4eead326._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_83236562._.js")
R.c("server/chunks/node_modules_zod_27f970bb._.js")
R.c("server/chunks/node_modules_better-auth_dist_ff97084b._.js")
R.c("server/chunks/node_modules_kysely_dist_esm_e0954e78._.js")
R.c("server/chunks/node_modules_drizzle-orm_68ac6ac0._.js")
R.c("server/chunks/node_modules_@neondatabase_serverless_index_mjs_2c73916b._.js")
R.c("server/chunks/node_modules_1c50c4fb._.js")
R.c("server/chunks/[root-of-the-server]__a06189c7._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_[___all]_route_actions_23e0180f.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
