var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(with-sidebar)/People/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_1f921924._.js")
R.c("server/chunks/ssr/[root-of-the-server]__67bbfeed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2baaa7c6._.js")
R.c("server/chunks/ssr/node_modules_@opentelemetry_api_build_esm_c2831320._.js")
R.c("server/chunks/ssr/node_modules_@swc_helpers_cjs__interop_require_wildcard_cjs_199dfdf0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f0336b73._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__31c4daa8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_c3cc2fff._.js")
R.c("server/chunks/ssr/node_modules_next_841fe23d._.js")
R.c("server/chunks/ssr/node_modules_@better-auth_core_dist_9ee9de5b._.js")
R.c("server/chunks/ssr/node_modules_jose_dist_webapi_19c08da9._.js")
R.c("server/chunks/ssr/node_modules_zod_80a8f58b._.js")
R.c("server/chunks/ssr/node_modules_better-auth_dist_5332adbd._.js")
R.c("server/chunks/ssr/node_modules_kysely_dist_esm_31f33e94._.js")
R.c("server/chunks/ssr/node_modules_drizzle-orm_371852ac._.js")
R.c("server/chunks/ssr/node_modules_@neondatabase_serverless_index_mjs_306c6d67._.js")
R.c("server/chunks/ssr/node_modules_8965c6ee._.js")
R.c("server/chunks/ssr/[root-of-the-server]__631ee6a2._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(with-sidebar)_People_page_actions_80f67b94.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/(with-sidebar)/People/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/app/(with-sidebar)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_10 => \"[project]/app/(with-sidebar)/People/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/(with-sidebar)/People/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/app/(with-sidebar)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_10 => \"[project]/app/(with-sidebar)/People/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
