import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// PPMondwest font
const ppMondwest = localFont({
  src: [
    {
      path: './fonts/ppmondwest-regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ppneuebit-bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-ppmondwest',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Pathfinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppMondwest.variable} antialiased`}
      >
        <main className="flex-1 overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}

