import { db } from '../../app/db';
import { internship } from '../../app/db/schema';

/**
 * Seed script for internship opportunities
 * Run with: tsx scripts/seed/seed-internships.ts
 */

const sampleInternships = [
  // Computer Science & Technology
  {
    title: 'Software Engineering Intern',
    company: 'Google',
    description: 'Join our team to work on cutting-edge technology projects. You\'ll collaborate with experienced engineers to design, develop, and deploy software solutions that impact millions of users worldwide.',
    requirements: '• Currently pursuing BS/MS in Computer Science or related field\n• Strong programming skills in Java, Python, or C++\n• Understanding of data structures and algorithms\n• Passion for technology and innovation',
    location: 'Mountain View, CA',
    locationType: 'hybrid',
    duration: 'Summer 2024 (12 weeks)',
    isPaid: true,
    salaryRange: '$45-55/hr',
    applicationDeadline: new Date('2024-03-01'),
    startDate: new Date('2024-06-01'),
    skills: ['Python', 'Java', 'Algorithms', 'Problem Solving', 'Git'],
    relatedMajors: ['Computer Science', 'Software Engineering', 'Computer Engineering'],
    relatedDegrees: ['B.S.', 'B.A.', 'M.S.'],
    experienceLevel: 'junior',
    applicationUrl: 'https://careers.google.com/students',
    contactEmail: 'university@google.com',
    isActive: true,
  },
  {
    title: 'Data Science Intern',
    company: 'Meta',
    description: 'Work with massive datasets to extract insights and build machine learning models. You\'ll contribute to projects that enhance user experience across Facebook, Instagram, and WhatsApp.',
    requirements: '• Pursuing degree in Data Science, Statistics, CS, or related field\n• Experience with Python and data analysis libraries (Pandas, NumPy)\n• Knowledge of machine learning fundamentals\n• Strong analytical and communication skills',
    location: 'Menlo Park, CA',
    locationType: 'onsite',
    duration: '3 months',
    isPaid: true,
    salaryRange: '$50-60/hr',
    applicationDeadline: new Date('2024-02-15'),
    startDate: new Date('2024-05-15'),
    skills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'Data Visualization'],
    relatedMajors: ['Data Science', 'Statistics', 'Computer Science', 'Mathematics'],
    relatedDegrees: ['B.S.', 'B.A.', 'M.S.'],
    experienceLevel: 'sophomore',
    applicationUrl: 'https://www.metacareers.com/students',
    contactEmail: 'recruiting@meta.com',
    isActive: true,
  },
  {
    title: 'Full Stack Developer Intern',
    company: 'Amazon Web Services',
    description: 'Build scalable web applications using modern technologies. You\'ll work on AWS services and tools, gaining hands-on experience with cloud computing and distributed systems.',
    requirements: '• Pursuing BS in Computer Science or related field\n• Experience with JavaScript, React, Node.js\n• Understanding of RESTful APIs and databases\n• Familiarity with cloud platforms (AWS preferred)',
    location: 'Seattle, WA',
    locationType: 'hybrid',
    duration: 'Summer 2024',
    isPaid: true,
    salaryRange: '$42-52/hr',
    applicationDeadline: new Date('2024-03-15'),
    startDate: new Date('2024-06-10'),
    skills: ['JavaScript', 'React', 'Node.js', 'AWS', 'MongoDB'],
    relatedMajors: ['Computer Science', 'Software Engineering', 'Information Technology'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'sophomore',
    applicationUrl: 'https://www.amazon.jobs/en/teams/internships-for-students',
    contactEmail: 'aws-intern@amazon.com',
    isActive: true,
  },
  {
    title: 'Cybersecurity Intern',
    company: 'Microsoft',
    description: 'Help protect Microsoft products and services from security threats. You will learn about threat detection, vulnerability assessment, and security best practices.',
    requirements: '• Pursuing degree in Cybersecurity, Computer Science, or related field\n• Basic understanding of network security and cryptography\n• Interest in ethical hacking and penetration testing\n• Security certifications (CompTIA Security+, CEH) a plus',
    location: 'Redmond, WA',
    locationType: 'hybrid',
    duration: '12 weeks',
    isPaid: true,
    salaryRange: '$40-50/hr',
    applicationDeadline: new Date('2024-02-28'),
    startDate: new Date('2024-06-01'),
    skills: ['Network Security', 'Penetration Testing', 'Python', 'Linux', 'Risk Assessment'],
    relatedMajors: ['Cybersecurity', 'Computer Science', 'Information Technology'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'junior',
    applicationUrl: 'https://careers.microsoft.com/students',
    contactEmail: 'university@microsoft.com',
    isActive: true,
  },
  {
    title: 'UX/UI Design Intern',
    company: 'Apple',
    description: 'Design intuitive and beautiful user interfaces for Apple products. You\'ll collaborate with product teams to create wireframes, prototypes, and final designs.',
    requirements: '• Pursuing degree in Design, HCI, or related field\n• Proficiency in Figma, Sketch, or Adobe XD\n• Strong portfolio demonstrating UI/UX work\n• Understanding of design principles and user-centered design',
    location: 'Cupertino, CA',
    locationType: 'onsite',
    duration: 'Summer 2024',
    isPaid: true,
    salaryRange: '$38-48/hr',
    applicationDeadline: new Date('2024-03-10'),
    startDate: new Date('2024-06-15'),
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research', 'Adobe Creative Suite'],
    relatedMajors: ['Graphic Design', 'UX Design', 'Human-Computer Interaction'],
    relatedDegrees: ['B.S.', 'B.A.', 'B.F.A.'],
    experienceLevel: 'any',
    applicationUrl: 'https://www.apple.com/careers/us/students.html',
    contactEmail: 'college@apple.com',
    isActive: true,
  },
  
  // Business & Finance
  {
    title: 'Investment Banking Summer Analyst',
    company: 'Goldman Sachs',
    description: 'Gain exposure to mergers & acquisitions, capital raising, and strategic advisory. You\'ll work on live deals and learn from senior bankers.',
    requirements: '• Pursuing BS/BA in Finance, Economics, Business, or related field\n• Strong analytical and financial modeling skills\n• Excellent Excel and PowerPoint skills\n• GPA 3.5 or higher preferred',
    location: 'New York, NY',
    locationType: 'onsite',
    duration: '10 weeks',
    isPaid: true,
    salaryRange: '$4,500/week',
    applicationDeadline: new Date('2024-01-31'),
    startDate: new Date('2024-06-01'),
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'M&A', 'PowerPoint'],
    relatedMajors: ['Finance', 'Economics', 'Business Administration', 'Accounting'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'junior',
    applicationUrl: 'https://www.goldmansachs.com/careers/students',
    contactEmail: 'campus-recruiting@gs.com',
    isActive: true,
  },
  {
    title: 'Marketing Analytics Intern',
    company: 'Procter & Gamble',
    description: 'Analyze consumer data and market trends to drive brand strategy. You\'ll use data analytics tools to generate insights and recommendations.',
    requirements: '• Pursuing degree in Marketing, Business Analytics, or related field\n• Proficiency in Excel and data visualization tools\n• Strong analytical and communication skills\n• Interest in consumer goods industry',
    location: 'Cincinnati, OH',
    locationType: 'hybrid',
    duration: '12 weeks',
    isPaid: true,
    salaryRange: '$28-35/hr',
    applicationDeadline: new Date('2024-02-20'),
    startDate: new Date('2024-05-20'),
    skills: ['Data Analysis', 'Excel', 'Tableau', 'Market Research', 'Communication'],
    relatedMajors: ['Marketing', 'Business Analytics', 'Business Administration'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'sophomore',
    applicationUrl: 'https://www.pg.com/careers/internships',
    contactEmail: 'recruiting@pg.com',
    isActive: true,
  },
  {
    title: 'Consulting Intern',
    company: 'McKinsey & Company',
    description: 'Work with Fortune 500 clients to solve complex business problems. You\'ll conduct research, analyze data, and present recommendations to senior executives.',
    requirements: '• Pursuing undergraduate or graduate degree in any field\n• Exceptional problem-solving and analytical skills\n• Strong communication and presentation abilities\n• Leadership experience and teamwork',
    location: 'Boston, MA',
    locationType: 'hybrid',
    duration: '10 weeks',
    isPaid: true,
    salaryRange: '$4,000/week',
    applicationDeadline: new Date('2024-02-01'),
    startDate: new Date('2024-06-15'),
    skills: ['Problem Solving', 'Data Analysis', 'PowerPoint', 'Strategic Thinking', 'Communication'],
    relatedMajors: ['Business Administration', 'Economics', 'Engineering', 'Liberal Arts'],
    relatedDegrees: ['B.S.', 'B.A.', 'M.B.A.'],
    experienceLevel: 'senior',
    applicationUrl: 'https://www.mckinsey.com/careers/students',
    contactEmail: 'recruiting@mckinsey.com',
    isActive: true,
  },
  
  // Engineering
  {
    title: 'Mechanical Engineering Intern',
    company: 'Tesla',
    description: 'Design and test components for electric vehicles. You\'ll work on product development, manufacturing processes, and quality assurance.',
    requirements: '• Pursuing BS in Mechanical Engineering\n• Proficiency in CAD software (SolidWorks, CATIA)\n• Understanding of thermodynamics and mechanics\n• Hands-on experience with prototyping',
    location: 'Fremont, CA',
    locationType: 'onsite',
    duration: 'Summer 2024',
    isPaid: true,
    salaryRange: '$35-45/hr',
    applicationDeadline: new Date('2024-03-01'),
    startDate: new Date('2024-05-15'),
    skills: ['CAD', 'SolidWorks', 'Manufacturing', 'Prototyping', 'Testing'],
    relatedMajors: ['Mechanical Engineering', 'Aerospace Engineering'],
    relatedDegrees: ['B.S.'],
    experienceLevel: 'sophomore',
    applicationUrl: 'https://www.tesla.com/careers/students',
    contactEmail: 'intern@tesla.com',
    isActive: true,
  },
  {
    title: 'Civil Engineering Intern',
    company: 'AECOM',
    description: 'Assist in infrastructure projects including roads, bridges, and water systems. You\'ll use engineering software and work with project teams.',
    requirements: '• Pursuing BS in Civil Engineering\n• Knowledge of AutoCAD and Civil 3D\n• Understanding of structural analysis and design\n• Strong attention to detail',
    location: 'Los Angeles, CA',
    locationType: 'hybrid',
    duration: '3 months',
    isPaid: true,
    salaryRange: '$25-32/hr',
    applicationDeadline: new Date('2024-03-15'),
    startDate: new Date('2024-06-01'),
    skills: ['AutoCAD', 'Civil 3D', 'Structural Analysis', 'Project Management'],
    relatedMajors: ['Civil Engineering', 'Environmental Engineering'],
    relatedDegrees: ['B.S.'],
    experienceLevel: 'any',
    applicationUrl: 'https://careers.aecom.com/students',
    contactEmail: 'recruiting@aecom.com',
    isActive: true,
  },
  
  // Healthcare & Life Sciences
  {
    title: 'Clinical Research Intern',
    company: 'Mayo Clinic',
    description: 'Support clinical trials and research studies. You\'ll assist with data collection, patient recruitment, and regulatory compliance.',
    requirements: '• Pursuing degree in Biology, Health Sciences, or related field\n• Interest in clinical research and healthcare\n• Strong organizational and communication skills\n• Attention to detail and ethical conduct',
    location: 'Rochester, MN',
    locationType: 'onsite',
    duration: '12 weeks',
    isPaid: true,
    salaryRange: '$18-22/hr',
    applicationDeadline: new Date('2024-02-28'),
    startDate: new Date('2024-06-01'),
    skills: ['Clinical Research', 'Data Entry', 'Patient Care', 'Compliance', 'Communication'],
    relatedMajors: ['Biology', 'Health Sciences', 'Pre-Med', 'Nursing'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'any',
    applicationUrl: 'https://jobs.mayoclinic.org/students',
    contactEmail: 'education@mayo.edu',
    isActive: true,
  },
  {
    title: 'Pharmaceutical Research Intern',
    company: 'Pfizer',
    description: 'Conduct laboratory research to develop new medications. You\'ll work on drug discovery, formulation, and testing under the guidance of senior scientists.',
    requirements: '• Pursuing BS/MS in Chemistry, Biochemistry, or Pharmaceutical Sciences\n• Laboratory experience and knowledge of analytical techniques\n• Strong scientific writing skills\n• Ability to work independently and in teams',
    location: 'New York, NY',
    locationType: 'onsite',
    duration: 'Summer 2024',
    isPaid: true,
    salaryRange: '$22-30/hr',
    applicationDeadline: new Date('2024-03-01'),
    startDate: new Date('2024-05-20'),
    skills: ['Laboratory Research', 'Analytical Chemistry', 'Scientific Writing', 'HPLC', 'Data Analysis'],
    relatedMajors: ['Chemistry', 'Biochemistry', 'Pharmaceutical Sciences'],
    relatedDegrees: ['B.S.', 'M.S.'],
    experienceLevel: 'junior',
    applicationUrl: 'https://www.pfizer.com/careers/students',
    contactEmail: 'university.recruiting@pfizer.com',
    isActive: true,
  },
  
  // Creative & Media
  {
    title: 'Graphic Design Intern',
    company: 'Nike',
    description: 'Create visual designs for marketing campaigns, product launches, and brand initiatives. You\'ll work with creative teams to bring ideas to life.',
    requirements: '• Pursuing degree in Graphic Design or related field\n• Proficiency in Adobe Creative Suite\n• Strong portfolio showcasing design work\n• Understanding of brand identity and visual communication',
    location: 'Portland, OR',
    locationType: 'hybrid',
    duration: '10 weeks',
    isPaid: true,
    salaryRange: '$22-28/hr',
    applicationDeadline: new Date('2024-03-10'),
    startDate: new Date('2024-06-01'),
    skills: ['Adobe Illustrator', 'Photoshop', 'InDesign', 'Typography', 'Branding'],
    relatedMajors: ['Graphic Design', 'Visual Arts', 'Marketing'],
    relatedDegrees: ['B.F.A.', 'B.A.'],
    experienceLevel: 'any',
    applicationUrl: 'https://jobs.nike.com/students',
    contactEmail: 'talent@nike.com',
    isActive: true,
  },
  {
    title: 'Content Writing Intern',
    company: 'HubSpot',
    description: 'Write blog posts, social media content, and marketing materials. You\'ll learn about content strategy, SEO, and digital marketing.',
    requirements: '• Pursuing degree in English, Journalism, Communications, or related field\n• Excellent writing and editing skills\n• Basic understanding of SEO and content marketing\n• Creativity and attention to detail',
    location: 'Boston, MA',
    locationType: 'remote',
    duration: '3 months',
    isPaid: true,
    salaryRange: '$20-25/hr',
    applicationDeadline: new Date('2024-03-20'),
    startDate: new Date('2024-06-10'),
    skills: ['Content Writing', 'SEO', 'Copywriting', 'Social Media', 'Content Strategy'],
    relatedMajors: ['English', 'Journalism', 'Communications', 'Marketing'],
    relatedDegrees: ['B.A.', 'B.S.'],
    experienceLevel: 'any',
    applicationUrl: 'https://www.hubspot.com/careers/students',
    contactEmail: 'jobs@hubspot.com',
    isActive: true,
  },
  
  // Remote/Startup Opportunities
  {
    title: 'Product Management Intern',
    company: 'Stripe',
    description: 'Help shape product strategy for payment processing solutions. You\'ll work with engineers and designers to build features that serve millions of businesses.',
    requirements: '• Pursuing degree in Business, CS, or related field\n• Interest in product management and technology\n• Strong analytical and communication skills\n• Entrepreneurial mindset',
    location: 'Remote',
    locationType: 'remote',
    duration: '12 weeks',
    isPaid: true,
    salaryRange: '$40-50/hr',
    applicationDeadline: new Date('2024-03-05'),
    startDate: new Date('2024-06-01'),
    skills: ['Product Management', 'Market Analysis', 'User Research', 'Agile', 'Communication'],
    relatedMajors: ['Business Administration', 'Computer Science', 'Engineering'],
    relatedDegrees: ['B.S.', 'B.A.'],
    experienceLevel: 'junior',
    applicationUrl: 'https://stripe.com/jobs/university',
    contactEmail: 'university@stripe.com',
    isActive: true,
  },
  {
    title: 'Social Media Marketing Intern',
    company: 'Airbnb',
    description: 'Manage social media accounts and create engaging content. You\'ll analyze metrics, run campaigns, and interact with our global community.',
    requirements: '• Pursuing degree in Marketing, Communications, or related field\n• Experience with social media platforms and analytics\n• Creative mindset and excellent communication\n• Understanding of digital marketing trends',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    duration: 'Summer 2024',
    isPaid: true,
    salaryRange: '$25-32/hr',
    applicationDeadline: new Date('2024-03-15'),
    startDate: new Date('2024-05-25'),
    skills: ['Social Media', 'Content Creation', 'Analytics', 'Copywriting', 'Community Management'],
    relatedMajors: ['Marketing', 'Communications', 'Digital Media'],
    relatedDegrees: ['B.A.', 'B.S.'],
    experienceLevel: 'any',
    applicationUrl: 'https://careers.airbnb.com/students',
    contactEmail: 'recruiting@airbnb.com',
    isActive: true,
  },
];

async function seedInternships() {
  console.log('🌱 Starting internship seed...');

  try {
    console.log(`📝 Inserting ${sampleInternships.length} internships...`);
    
    for (const internshipData of sampleInternships) {
      await db.insert(internship).values(internshipData);
      console.log(`✅ Added: ${internshipData.title} at ${internshipData.company}`);
    }

    console.log('\n✨ Internship seed completed successfully!');
    console.log(`📊 Total internships added: ${sampleInternships.length}`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding internships:', error);
    process.exit(1);
  }
}

// Run the seed function
seedInternships();
